import type { IConversation } from "./types";

const now = Date.now();

export const MOCK_CONVERSATIONS: IConversation[] = [
  {
    id: "c-1",
    kind: "lot",
    title: "Vintage Leica M6",
    subtitle: "Lot #2841 · Questions",
    peerUserName: "LensCraft_UA",
    lastPreview: "Shipping to EU is insured via our partner.",
    lastAt: new Date(now - 8 * 60 * 1000).toISOString(),
    unreadCount: 2,
    messages: [
      {
        id: "m1",
        userName: "LensCraft_UA",
        message: "Hi — happy to answer anything before you bid.",
        timestamp: new Date(now - 45 * 60 * 1000).toISOString(),
        role: "seller",
      },
      {
        id: "m2",
        userName: "You",
        message: "Does the body have brassing on the top plate?",
        timestamp: new Date(now - 40 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "LensCraft_UA",
        message: "Light brassing near the strap lugs only. I can send macro photos if needed.",
        timestamp: new Date(now - 35 * 60 * 1000).toISOString(),
        role: "seller",
      },
      {
        id: "m4",
        userName: "LensCraft_UA",
        message: "Shipping to EU is insured via our partner.",
        timestamp: new Date(now - 8 * 60 * 1000).toISOString(),
        role: "seller",
      },
    ],
  },
  {
    id: "c-2",
    kind: "direct",
    title: "Oleksandr Petrenko",
    subtitle: "Direct message",
    peerUserName: "Oleksandr Petrenko",
    lastPreview: "Thanks, I'll review the invoice tonight.",
    lastAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "Oleksandr Petrenko",
        message: "Can we settle the escrow release timing for Friday?",
        timestamp: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        userName: "You",
        message: "Friday works if support confirms by noon.",
        timestamp: new Date(now - 28 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "Oleksandr Petrenko",
        message: "Thanks, I'll review the invoice tonight.",
        timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "c-3",
    kind: "lot",
    title: "Omega Speedmaster 3861",
    subtitle: "Lot #9102",
    peerUserName: "ChronoVault",
    lastPreview: "You: Sounds good.",
    lastAt: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "ChronoVault",
        message: "Box & papers included. Service history from 2023.",
        timestamp: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
        role: "seller",
      },
      {
        id: "m2",
        userName: "You",
        message: "Sounds good.",
        timestamp: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
    {
    id: "c-5",
    kind: "direct",
    title: "Oleksandr Petrenko",
    subtitle: "Direct message",
    peerUserName: "Oleksandr Petrenko",
    lastPreview: "Thanks, I'll review the invoice tonight.",
    lastAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "Oleksandr Petrenko",
        message: "Can we settle the escrow release timing for Friday?",
        timestamp: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        userName: "You",
        message: "Friday works if support confirms by noon.",
        timestamp: new Date(now - 28 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "Oleksandr Petrenko",
        message: "Thanks, I'll review the invoice tonight.",
        timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
    {
    id: "c-6",
    kind: "direct",
    title: "Oleksandr Petrenko",
    subtitle: "Direct message",
    peerUserName: "Oleksandr Petrenko",
    lastPreview: "Thanks, I'll review the invoice tonight.",
    lastAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "Oleksandr Petrenko",
        message: "Can we settle the escrow release timing for Friday?",
        timestamp: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        userName: "You",
        message: "Friday works if support confirms by noon.",
        timestamp: new Date(now - 28 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "Oleksandr Petrenko",
        message: "Thanks, I'll review the invoice tonight.",
        timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
    {
    id: "c-7",
    kind: "direct",
    title: "Oleksandr Petrenko",
    subtitle: "Direct message",
    peerUserName: "Oleksandr Petrenko",
    lastPreview: "Thanks, I'll review the invoice tonight.",
    lastAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "Oleksandr Petrenko",
        message: "Can we settle the escrow release timing for Friday?",
        timestamp: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        userName: "You",
        message: "Friday works if support confirms by noon.",
        timestamp: new Date(now - 28 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "Oleksandr Petrenko",
        message: "Thanks, I'll review the invoice tonight.",
        timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
    {
    id: "c-8",
    kind: "direct",
    title: "Oleksandr Petrenko",
    subtitle: "Direct message",
    peerUserName: "Oleksandr Petrenko",
    lastPreview: "Thanks, I'll review the invoice tonight.",
    lastAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "Oleksandr Petrenko",
        message: "Can we settle the escrow release timing for Friday?",
        timestamp: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        userName: "You",
        message: "Friday works if support confirms by noon.",
        timestamp: new Date(now - 28 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "Oleksandr Petrenko",
        message: "Thanks, I'll review the invoice tonight.",
        timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
    {
    id: "c-9",
    kind: "direct",
    title: "Oleksandr Petrenko",
    subtitle: "Direct message",
    peerUserName: "Oleksandr Petrenko",
    lastPreview: "Thanks, I'll review the invoice tonight.",
    lastAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: "m1",
        userName: "Oleksandr Petrenko",
        message: "Can we settle the escrow release timing for Friday?",
        timestamp: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m2",
        userName: "You",
        message: "Friday works if support confirms by noon.",
        timestamp: new Date(now - 28 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "m3",
        userName: "Oleksandr Petrenko",
        message: "Thanks, I'll review the invoice tonight.",
        timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
];
