import type { IProfileWardrobeResponse, IProfileWearable } from "./profileHome.types";

export const MOCK_PROFILE_WEARABLES: IProfileWearable[] = [
  {
    id: "auction_bomber",
    slot: "clothes",
    name: "Auction Bomber",
    description: "Куртка продавця для тих, хто виставив перший лот.",
    rarity: "rare",
    unlockedByBadgeType: "first_listing",
    isUnlocked: false,
    isEquipped: false,
  },
  {
    id: "elite_turtleneck",
    slot: "clothes",
    name: "Elite Turtleneck",
    description: "Мінімалістичний luxury-fit для елітних продавців.",
    rarity: "epic",
    unlockedByBadgeType: "seller_50",
    isUnlocked: false,
    isEquipped: false,
  },
  {
    id: "power_coat",
    slot: "clothes",
    name: "Power Seller Coat",
    description: "Темне пальто для користувачів із 100+ продажами.",
    rarity: "legendary",
    unlockedByBadgeType: "power_seller",
    isUnlocked: false,
    isEquipped: false,
  },
  {
    id: "verified_frame",
    slot: "frame",
    name: "Verified Blue Frame",
    description: "Фірмова синя рамка після верифікації.",
    rarity: "epic",
    unlockedByBadgeType: "verified",
    isUnlocked: true,
    isEquipped: false,
  },
  {
    id: "velvet_rope_frame",
    slot: "frame",
    name: "Velvet Rope Frame",
    description: "VIP-рамка для досвідченого продавця.",
    rarity: "rare",
    unlockedByBadgeType: "seller_10",
    isUnlocked: true,
    isEquipped: false,
  },
  {
    id: "crown_lot",
    slot: "headwear",
    name: "Lot Crown",
    description: "Корона за першу перемогу на аукціоні.",
    rarity: "rare",
    unlockedByBadgeType: "first_win",
    isUnlocked: false,
    isEquipped: false,
  },
  {
    id: "collector_shades",
    slot: "accessory",
    name: "Collector Shades",
    description: "Окуляри колекціонера за серію виграних лотів.",
    rarity: "rare",
    unlockedByBadgeType: "collector",
    isUnlocked: false,
    isEquipped: false,
  },
  {
    id: "diamond_earring",
    slot: "accessory",
    name: "Diamond Earring",
    description: "Маленький блиск для серйозного колекціонера.",
    rarity: "epic",
    unlockedByBadgeType: "patron",
    isUnlocked: true,
    isEquipped: false,
  },
  {
    id: "laurel_pin",
    slot: "accessory",
    name: "Laurel Pin",
    description: "Золотий лацкан-пін за 10+ продажів.",
    rarity: "rare",
    unlockedByBadgeType: "seller_10",
    isUnlocked: true,
    isEquipped: false,
  },
];

export const MOCK_PROFILE_WARDROBE_RESPONSE: IProfileWardrobeResponse = {
  totalCount: 9,
  wearables: MOCK_PROFILE_WEARABLES,
};
