import type { IProfileBadgesResponse } from "./profileHome.types";

export const MOCK_PROFILE_BADGES_RESPONSE: IProfileBadgesResponse = {
  badges: [
    {
      badgeType: "welcome",
      badgeRare: "common",
      badgeTitle: "На платформі",
      badgeDescription: "Приєдналися до AuctiqueBids і почали свій шлях.",
      isCollected: true,
      isFavourite: true,
    },
    {
      badgeType: "veteran",
      badgeRare: "rare",
      badgeTitle: "Рік разом",
      badgeDescription: "Повний рік активності на платформі.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "anniversary",
      badgeRare: "epic",
      badgeTitle: "Два роки легенди",
      badgeDescription: "Два роки як активний учасник спільноти.",
      isCollected: true,
      isFavourite: true,
    },
    {
      badgeType: "first_listing",
      badgeRare: "common",
      badgeTitle: "Перший лот",
      badgeDescription: "Виставили або продали перший лот.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "seller_10",
      badgeRare: "rare",
      badgeTitle: "Досвідчений продавець",
      badgeDescription: "Завершили 10+ продажів лотів.",
      isCollected: true,
      isFavourite: true,
    },
    {
      badgeType: "seller_50",
      badgeRare: "epic",
      badgeTitle: "Елітний продавець",
      badgeDescription: "Завершили 50+ продажів лотів.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "power_seller",
      badgeRare: "legendary",
      badgeTitle: "Силовий продавець",
      badgeDescription: "Завершили 100+ продажів — вищий рівень.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "first_win",
      badgeRare: "common",
      badgeTitle: "Перша перемога",
      badgeDescription: "Виграли перший лот на аукціоні.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "collector",
      badgeRare: "rare",
      badgeTitle: "Колекціонер",
      badgeDescription: "Виграли 10+ лотів на аукціоні.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "patron",
      badgeRare: "epic",
      badgeTitle: "Меценат",
      badgeDescription: "Виграли 25+ лотів — серйозний колекціонер.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "verified",
      badgeRare: "epic",
      badgeTitle: "Верифікований",
      badgeDescription: "Особу та статус продавця підтверджено платформою.",
      isCollected: true,
      isFavourite: false,
    },
    {
      badgeType: "trust_90",
      badgeRare: "legendary",
      badgeTitle: "Золота довіра",
      badgeDescription: "Рейтинг довіри 90+ — зразкова репутація.",
      isCollected: true,
      isFavourite: true,
    },
  ],
  achievements: {
    collected: 12,
    total: 12,
    percent: 100,
    byRarity: [
      { rarity: "common", collected: 3, total: 3 },
      { rarity: "rare", collected: 4, total: 4 },
      { rarity: "epic", collected: 3, total: 3 },
      { rarity: "legendary", collected: 2, total: 2 },
    ],
  },
};
